swagger: '2.0'
info:
  title: flow API
  description: flow version - not yet reached
  version: 0.1.1
host: localhost:8881
schemes:
  - http
basePath: /
produces:
  - application/json
paths:
  /users/login:
    get:
      summary: Get the aid of a user
      parameters:
        - name: username
          in: query
          description: The username of the user
          required: true
          type: string
        - name: password
          in: query
          description: The password of the user
          required: true
          type: string
      tags:
        - Users
      responses:
        200:
          description: A json object
          schema:
            type: object
            properties:
              aid:
                type: string
        400:
          $ref: '#/responses/400'
    post:
      summary: Get the aid of a user
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            properties:
              username:
                type: string
              password:
                type: string
      tags:
        - Users
      responses:
        200:
          description: A json object
          schema:
            type: object
            properties:
              aid:
                type: string
        400:
          $ref: '#/responses/400'
  /users/join:
    get:
      summary: Create a user account
      parameters:
        - name: username
          in: query
          description: The username of the user
          required: true
          type: string
        - name: password
          in: query
          description: The password of the user
          required: true
          type: string
      tags:
        - Users
      responses:
        200:
          description: A json object
          schema:
            type: object
            properties:
              aid:
                type: string
        400:
          $ref: '#/responses/400'
    post:
      summary: Create a user account
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            properties:
              username:
                type: string
              password:
                type: string
      tags:
        - Users
      responses:
        200:
          description: A json object
          schema:
            type: object
            properties:
              aid:
                type: string
        400:
          $ref: '#/responses/400'
  /users/metrics:
    get:
      summary: Get the latest metrics on users
      responses:
        200:
          description: a json object
          schema:
            type: object
            properties:
              RegisteredUsers:
                type: number
  /users/username:
    get:
      summary: Get the username of an user
      parameters:
        - name: aid
          in: query
          description: The aid of the user
          required: true
          type: string
      tags:
        - Users
      responses:
        200:
          description: A json object
          schema:
            type: object
            properties:
              username:
                type: string
        400:
          $ref: '#/responses/400'
    post:
      summary: Get the username of an user
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            properties:
              aid:
                type: string
      tags:
        - Users
      responses:
        200:
          description: A json object
          schema:
            type: object
            properties:
              username:
                type: string
        400:
          $ref: '#/responses/400'
  /users/last_login:
    get:
      summary: Get the last time a user logged in
      parameters:
        - name: aid
          in: query
          description: The aid of the user
          required: true
          type: string
      tags:
        - Users
      responses:
        200:
          description: A json object
          schema:
            type: object
            properties:
              last_login:
                type: string
                format: date-time
        400:
          $ref: '#/responses/400'
    post:
      summary: Get the last time a user logged in
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            properties:
              aid:
                type: string
      tags:
        - Users
      responses:
        200:
          description: A json object
          schema:
            type: object
            properties:
              last_login:
                type: string
                format: date-time
        400:
          $ref: '#/responses/400'
responses:
  400:
    description: Error
    schema:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        fields:
          type: string